# This is a config for E2B sandbox template.
# You can use template ID (0ytyv5jqu1fltb24d4cv) or template name (nectar-nextjs-15) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nectar-nextjs-15") # Sync sandbox
# sandbox = await AsyncSandbox.create("nectar-nextjs-15") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nectar-nextjs-15')

team_id = "f00366b2-b8c1-410d-917f-73fb26dd4624"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nectar-nextjs-15"
template_id = "0ytyv5jqu1fltb24d4cv"
